services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./react-app
    ports:
      - "3000:80"
    depends_on:
      - backend
