services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"
    volumes:
      - .:/react-app
      - /react-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for React fast refresh inside Docker
    #env_file:
      #- ./.env
  
  # docker-compose -f docker-compose.dev.yml up

