apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabai-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fabai
  template:
    metadata:
      labels:
        app: fabai
    spec:
      containers:
      - name: fabai
        image: fabai        # This refers to your local Docker image
        ports:
        - containerPort: 5000
