name: Windows CI for NPM and python

on:
  push:
    branches: [ main, Database ]
  pull_request:
    branches: [ main, Database ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Python backend setup
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Node.js frontend setup
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run tests
      working-directory: ./react-app
      run: |
        npm install
        npm run build
